runtime: python39  # Or the Python version you are using

# Entry point for the application
entrypoint: gunicorn -b :$PORT backend:app

# Environment variables
env_variables:
  FLASK_ENV: "production"

# Instance class and scaling settings (optional)
# instance_class: F1
# automatic_scaling:
#   max_instances: 1
